"""Render a CopilotReport into downloadable PDFs — one for the tailored résumé,
one for the cover letter (they're submitted separately).

Uses fpdf2 with the **standard-14 font** Helvetica: it's part of the PDF spec, so
fpdf2 embeds the metrics and the viewer supplies the glyphs — NO system fonts and
NO bundled .ttf required, on any host. The one tradeoff is Latin-1 coverage, so we
sanitize the smart punctuation LLMs emit (em-dashes, curly quotes). To go full
Unicode later, bundle a TTF and swap set_font for add_font().

Note: the résumé PDF deliberately OMITS the honesty note — that's internal guidance
for the candidate (what was NOT claimed), not something to submit.
"""

from __future__ import annotations

from fpdf import FPDF

from .models import CopilotReport

_SUBS = {
    "—": "-",
    "–": "-",
    "‘": "'",
    "’": "'",
    "“": '"',
    "”": '"',
    "…": "...",
    "•": "-",
    " ": " ",
    "−": "-",
    "‐": "-",
    "‑": "-",
}


def _clean(text: str) -> str:
    for k, v in _SUBS.items():
        text = text.replace(k, v)
    return text.encode("latin-1", "replace").decode("latin-1")


class _PDF(FPDF):
    def footer(self) -> None:
        self.set_y(-12)
        self.set_font("Helvetica", size=7)
        self.set_text_color(150, 150, 150)
        self.cell(0, 8, "Generated by ai-job-copilot", align="C")


def _new_pdf() -> _PDF:
    pdf = _PDF(format="A4")
    pdf.set_auto_page_break(auto=True, margin=16)
    pdf.set_margins(18, 16, 18)
    pdf.add_page()
    return pdf


def _title(pdf: _PDF, text: str) -> None:
    pdf.set_font("Helvetica", "B", 16)
    pdf.set_text_color(15, 15, 15)
    pdf.multi_cell(0, 8, _clean(text))


def _heading(pdf: _PDF, text: str) -> None:
    pdf.ln(2)
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(30, 30, 30)
    pdf.multi_cell(0, 7, _clean(text))
    pdf.ln(1)


def _body(pdf: _PDF, text: str, size: float = 10.5) -> None:
    pdf.set_font("Helvetica", size=size)
    pdf.set_text_color(45, 45, 45)
    pdf.multi_cell(0, 5.5, _clean(text))


def _role_line(report: CopilotReport) -> str:
    company = f" — {report.posting.company}" if report.posting.company else ""
    return report.posting.title + company


def render_resume_pdf(report: CopilotReport) -> bytes:
    """Tailored résumé: summary + role-aligned bullets. No honesty note (internal)."""
    pdf = _new_pdf()
    _title(pdf, _role_line(report))
    _heading(pdf, "Summary")
    _body(pdf, report.resume.summary)
    _heading(pdf, "Experience")
    for b in report.resume.bullets:
        _body(pdf, f"-  {b.tailored}")
        pdf.ln(0.5)
    return bytes(pdf.output())


def render_cover_letter_pdf(report: CopilotReport) -> bytes:
    """The cover letter as its own document."""
    pdf = _new_pdf()
    _title(pdf, f"Cover Letter — {_role_line(report)}")
    pdf.ln(2)
    _body(pdf, report.kit.cover_letter, size=11)
    return bytes(pdf.output())
